# Generated by Django 6.0.7 on 2026-09-19 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'guruh', 'verbose_name_plural': 'guruhlar'},
        ),
    ]
